package analizadorJCC;

/* Generated By:JavaCC: Do not edit this line. CorreoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CorreoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CADENA = 6;
  /** RegularExpression Id. */
  int CARACTER = 7;
  /** RegularExpression Id. */
  int SEPARADOR = 8;
  /** RegularExpression Id. */
  int PUNTO = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<CADENA>",
    "<CARACTER>",
    "\"@\"",
    "\".\"",
  };

}
